const constants = {
    homeMessage: `We are at the heart of appropriate care`,
    coachLogin: `Login as Life Coach`,
    userLogin: `Login as User`,
    coachImg: `../../assets/Images/LifeCoachLogIn.jpg`,
    userImg: `../../assets/Images/UserLogIn.jpg`,
    maleImg: `../../assets/Images/male.png`,
    femaleImg: `../../assets/Images/female.png`,
    appointmentAlreadyExist: `There is an appointment in this slot already`,
    noAppointments: `You haven't made any appointments yet`,
    noSchedules: `No planned schedules yet`,
    userRegistrationFailed: `You were not able to register as a user`,
    coachRegistrationFailed: `You were not able to register as a coach`,
    userExist: `User exists with same email Id`,
    coachExist: `Coach exists with same name`,
    invalid: `Invalid Credentials`,
    notepadImg: `../../assets/Images/Notepad_icon.svg.png`,
    passwordError: `Password should have 5 to 10 characters`,
    nameError: `Name should have 3 to 50 characters`,
    ageError: `Age should be between 20 and 100 years`,
    mobileNumberError: `Mobile number should have 10 digits`,
    fieldRequired: 'This field is required',
    emailError : `Email Id should be valid`,
    specialityError: `Speciality should have atleast 10 characters`,
    accountCreated: `Account created successfully`,
    pinCodeError: `Pincode should have 6 digits`,
    cityError: `City should have 3 to 20 characters`,
    stateError: `State should have 3 to 20 characters`,
    countryError: `Country should have 3 to 20 characters`,
    appointmentDateError: `Date should be any upcoming 7 days`,
    appointmentScheduled: `Your appointment is scheduled successfully`,
    appointmentRescheduled: `Your appointment is rescheduled successfully`,
    appointmentCancelled: `Your appointment is cancelled successfully`,
    cancelConfirm: `Are you sure you need to cancel the appointment?`,
    noCoaches:`No coaches currently available`
};

export default constants;
